# Site settings
title: Ahmad Rushdi
email: rushdye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple and clean design. Wordpress theme, minimalist design, blog design, graphic design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arynet.github.io/" # the base hostname & protocol for your site

# Build settings
permalink: /:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
